appblocks-hub/BB-CLI

auth.js
bin/index.js
package.json
subcommands/pr/index.js
subcommands/pr/util.js
subcommands/pull/forkUtil.js
templates/pull-request/genetatePrTemplate.js
templates/pull-request/pull_request_template.md
utils/Mutations.js
utils/api.js

This PR includes changes made to bring PR creation flow to BB-CLI.

Fork PR flow

---

bin/index.js
subcommands/publish.js
subcommands/publish/dependencyUtil.js
subcommands/runtime/update/index.js
subcommands/runtime/util.js
subcommands/sync.js
utils/api.js
utils/axios/index.js
utils/createBlock.js
utils/registerBlock.js

Run time selection 
save dependencies etc..

Dependencies and runtime

---

bin/index.js
subcommands/addCategories.js
subcommands/addTags.js
subcommands/appPublish.js
subcommands/create.js
subcommands/log.js
subcommands/port-check.js
subcommands/pr/util.js
subcommands/publish.js
subcommands/pull.js
subcommands/push.js
subcommands/push_config.js
subcommands/runtime/update/index.js
subcommands/runtime/util.js
subcommands/start.js
subcommands/stop.js
subcommands/sync.js
templates/createTemplates/function-templates/generate-readme.js
templates/createTemplates/function-templates/index.js
templates/createTemplates/uiContainer-templates/generate-readme.js
templates/createTemplates/uiContainer-templates/index.js
templates/createTemplates/uiElement-templates/generate-readme.js
templates/createTemplates/uiElement-templates/index.js
utils/appconfig-manager.js
utils/createComponent.js
utils/pushBlocks.js
utils/questionPrompts.js

All commands can now be run from inside the block directory.
add-tags, add-categories, publish and pr flow fixed to match new config paths
cli stuck during PR creation- fixed
readme was not getting created for function type-fixed
CLI expects VsCode to be present and 'code' to be in path. CLI tries to open PR template md in vscode. if not present user will have to go to the displayed path and edit manually.

Standalone block improvements

---

subcommands/init/index.js
subcommands/init/initializePackageBlock.js
subcommands/start/envToObj.js
subcommands/start/index.js
subcommands/start/watchCompilation.js
templates/createTemplates/uiContainer-templates/generate-packageJson.js
templates/createTemplates/uiElement-templates/generate-packageJson.js
templates/simple-todo-template/functions/addTodo/package.json
templates/simple-todo-template/functions/listTodos/package.json
templates/simple-todo-template/functions/removeTodo/package.json
templates/simple-todo-template/view/container/todoContainer/package.json
templates/simple-todo-template/view/elements/todoInput/package.json
templates/simple-todo-template/view/elements/todoItem/package.json

1. Local registry missing space_id & space_name values
2. env not loaded ( old node-sdk version)

Fixes ( local registry missing space_id)

---

subcommands/use.js
utils/preActionRunner.js

1. User login is ensured before use command - to prevent api call with "undefined" as  token in header
2. Current space name is checked prior, to avoid showing " current space name is undefined"

fix: undefined current space

---

subcommands/deploy/onPrem/awsFargate/index.js
subcommands/deploy/onPrem/awsStaticWeb/index.js
subcommands/deploy/onPrem/util.js
subcommands/upload/onPrem/awsECR/util.js
utils/aws/elb/index.js

shared function was not deployed with regular functions
Fixes # (issue)
Manual testing

Fix shared function deployment

---

subcommands/create.js
subcommands/port-check.js
subcommands/start/singleBuild/generateElementsEmulator/generateWebpackConfig.js
subcommands/start/singleBuild/index.js
subcommands/start/singleBuild/mergeDatas.js
subcommands/start/singleBuild/util.js
templates/createTemplates/uiContainer-templates/generate-packageJson.js
templates/createTemplates/uiElement-templates/generate-appJs.js
templates/createTemplates/uiElement-templates/generate-packageJson.js
utils/appconfig-manager.js
utils/blockTypes.js

Single build dependency library
Manual testing

feat: dependency library for single build

---

subcommands/create.js
subcommands/port-check.js
subcommands/start/singleBuild/generateElementsEmulator/generateWebpackConfig.js
subcommands/start/singleBuild/index.js
subcommands/start/singleBuild/mergeDatas.js
subcommands/start/singleBuild/util.js
subcommands/upload/onPrem/awsECR/util.js
templates/createTemplates/uiContainer-templates/generate-packageJson.js
templates/createTemplates/uiElement-templates/generate-appJs.js
templates/createTemplates/uiElement-templates/generate-packageJson.js
utils/appconfig-manager.js
utils/aws/util.js
utils/blockTypes.js
utils/index.js

Fix for mac docker build format on deployment 
Manual testing

Fix for mac docker build format on deployment 

---

package.json
subcommands/create.js
subcommands/syncV2.js
subcommands/syncV2/plugins/reRegisterBlocksStrategy.js
subcommands/syncV2/plugins/registerNewBlocksStrategy.js
subcommands/syncV2/syncCore.js
templates/createTemplates/function-templates/generate-commitlintrc.js
templates/createTemplates/function-templates/generate-eslintrc.js
templates/createTemplates/function-templates/generate-packageJson.js
templates/createTemplates/function-templates/generate-prettierrc.js
templates/createTemplates/uiContainer-templates/generate-commitlintrc.js
templates/createTemplates/uiContainer-templates/generate-eslintrc.js
templates/createTemplates/uiContainer-templates/generate-packageJson.js
templates/createTemplates/uiContainer-templates/generate-prettierrc.js
templates/createTemplates/uiElement-templates/generate-commitlintrc.js
templates/createTemplates/uiElement-templates/generate-eslintrc.js
templates/createTemplates/uiElement-templates/generate-packageJson.js
templates/createTemplates/uiElement-templates/generate-prettierrc.js
utils/appconfig-manager.js
utils/axiosInstances.js
utils/checkAndSetAuth.js
utils/fileAndFolderHelpers.js
utils/getHeaders.js
utils/getSignedInUser.js
utils/gitCheckUtils.js
utils/gitmanager.js
utils/jsDoc/types.js
utils/loggerV2.js
utils/registryUtils.js
utils/sync-utils.js

- Git hooks (pre-commi & commit-msg) for blocks
- Inital Login error

Linitng & hooks

---

subcommands/createBlockVersion/index.js
subcommands/languageVersion/util.js
subcommands/publish/dependencyUtil.js
subcommands/publish/index.js
utils/api.js

fix dependency error on publish block
Please delete options that are not relevant.
Manual

fix: dependency error on publish block

---

bin/index.js
subcommands/createVersion/createPackageVersion.js
subcommands/createVersion/index.js
subcommands/publish/publishPackageBlock.js
subcommands/pull/index.js
utils/blockPusher.js
utils/errors/blockPushError.js
utils/pushBlocks.js

Fixed the minor bugs faced in publish and pull of the package block

fix: package block publish issues

---

bin/bb-start.cjs
bin/bb-test.js
bin/bb.cjs
configstore.js
subcommands/initV2/index.js
subcommands/initV2/init.js
subcommands/initV2/initCore.js
subcommands/initV2/plugins/identifyUniqueBlockNamePlugin.js
subcommands/initV2/plugins/setAppBlockVersionPlugin.js
subcommands/publish/util.js
subcommands/startV2/plugins/LockAndAssignPortsPlugin/LockAndAssignPortsPlugin.js
subcommands/startV2/startCore.js
utils/Queries.js
utils/axiosInstances.js
utils/createRepoV2.js
utils/errors/createRepoError.js
utils/jsDoc/types.js
utils/questionPrompts.js

if `process.env.BB_CLI_RUN_HEADLESS` is "true" (a string) , global.HEADLESS_CONFIGS will be set to data read from _headless-config.json_ in the project directory.
`init` refactored to plugin format

refactor: init refactor & headless setup

---

subcommands/upload/onPrem/awsECR/index.js
subcommands/upload/onPrem/awsECR/util.js

Feat to add custom command to dockerignore and docker file before the start command . 
Eg : add  "beforeDockerStartCommand": ["RUN npm install"], "dockerIgnore": [".git"] keys to deploy.config.json function deployment configuation

feat: custom dockerignore and dockerBeforeStart commands through config

---

subcommands/start/singleBuild/generateElementsEmulator/generateWebpackConfig.js

add extensions to resolve in webpack

fix: add extensions to resolve in webpack

---

subcommands/port-check.js
subcommands/start/index.js

dependencies install on each block for be single-build issue fix

fix: dependencies install on each block for be single-build

---

subcommands/createV2/createCore.d.ts
utils/configManagers/configFactory.d.ts
utils/configManagers/configFactory.js
utils/configManagers/configManager.d.ts
utils/configManagers/configManager.js

Change to make oackage inside package possible

refactor for config managers

---

bin/bb-exec.cjs
subcommands/exec.js
utils/configManagers/blockConfigManager.js
utils/configManagers/configFactory.d.ts
utils/configManagers/configFactory.js
utils/configManagers/configManager.d.ts
utils/configManagers/configManager.js
utils/configManagers/packageConfigManager.d.ts
utils/configManagers/packageConfigManager.js
utils/index.js

refactor: config managers

---

utils/configManagers/configManager.d.ts
utils/configManagers/configManager.js
utils/configManagers/packageConfigManager.d.ts
utils/configManagers/packageConfigManager.js

Updates for type declaration files

Type Declaration files updated

---

bin/bb-publish.cjs
bin/bb-sync.cjs
subcommands/createVersion/index.js
subcommands/publish/index.js
subcommands/publish/publishBlock.js
subcommands/publish/publishPackageBlock.js
subcommands/publish/util.js
subcommands/pushV2/plugins/HandleBeforePush.js
subcommands/pushV2/utils/blockPusher.js
subcommands/tempSync/index.js
templates/createTemplates/function-templates/generate-gitignore.js
utils/gitManagerV2.js
utils/syncBlocks.js

This pr includes update to publish command for compatible with new cli changes and nested package workflow. To use this new command follow the below instructions
Usage: bb-publish [options] [block-name]
Arguments:
block-name               Name of block to publish
Options:
-v, --version <version>  Version to publish
-h, --help               display help for command

feat: publish

---

bin/bb-get.cjs
bin/bb.cjs
subcommands/get/get.js
subcommands/get/index.js
utils/api.js
utils/axios/index.js
utils/registryUtils.js

1. `bb pull` command, which was previously used to get purchased/free blocks for using and for collaborating, is now split to **pul**l & **get**.
2. `bb pull` can be used for ***collaboration*** 
3.  `bb get` will be used for getting free/purchased blocks
4. `bb get @[space-name]/<block-name>` - to use the command. space name is optional and the current user space will be used as space name if user omits it.
```mermaid
flowchart TD;
A([Start])-->B[If user has not mentioned a space,\n use current user space];
B-->C{inside a block?};
C--Yes-->D([Abort]);
C--No-->E[get the block from the store];
E-->F[Recursively get all child blocks,\n if a pacakge block while updating,\n every configs with details for syncing];
F-->G([Stop])
```

bb get command

---

subcommands/tempSync/createBBModules/index.js
subcommands/tempSync/createBBModules/util.js
subcommands/tempSync/index.js
subcommands/tempSync/syncOrphanBranches/util.js

Reverts appblocks-hub/BB-CLI#151

Revert "fix: modified sync"

---

subcommands/createVersion/createBlockVersion.js
subcommands/createVersion/index.js
subcommands/pullV2/plugins/HandleBlockPull.js
subcommands/pullV2/plugins/HandleGetPullBlockDetails.js
subcommands/pullV2/utils/index.js
subcommands/tempSync/createBBModules/index.js
subcommands/tempSync/createBBModules/util.js
subcommands/tempSync/index.js
utils/getHeaders.js
utils/syncBlocks.js

1. fix: copying git issue on bb pull
2. fix: default branch diff check on bb create version
3. fix: only sync if there is pull while calling from create version
4. fix: shield header fix

fix issues

---

subcommands/get/get.js

1. success message on successful get

fix: feedback on successful get

---

bin/bb-push.cjs
bin/bb_command_descriptions.js
subcommands/ls.js
subcommands/pushV2/plugins/HandleBeforePush.js
subcommands/pushV2/plugins/HandleMonoRepoPush.js
subcommands/pushV2/plugins/HandleMultiRepoPush.js
subcommands/startV2/plugins/handleNodeFunctionStart/index.js

1. fix: ls showing incorrect url for function
2. refactor: mono repo for push all by default

fix push and ls command issues

---

subcommands/createVersion/createPackageVersion.js

This pr changes allow publishing package that doesn't have any member block.

publish a package block even without having any Member block

---

subcommands/pullV2/plugins/HandleAfterPull.js
subcommands/pullV2/plugins/HandleBeforePull.js
subcommands/pullV2/plugins/HandleGetPullBlockDetails.js
subcommands/pullV2/pullCore.js
subcommands/use.js
utils/checkAndSetUserSpacePreference.js
utils/registryUtils.js

Allow pulling of block from another space with access

fix: pull access issue from diff space with access

---

configstore.js
subcommands/pullV2/plugins/HandleBeforePull.js
subcommands/pullV2/plugins/HandleBlockPull.js
subcommands/pullV2/plugins/HandleGetPullBlockDetails.js
subcommands/use.js
utils/checkAndSetUserSpacePreference.js
utils/getHeaders.js

fix: bb pull access issue

---

bin/bb-rename.cjs
bin/bb.cjs
subcommands/blockRename/index.js
subcommands/blockRename/util.js
utils/Queries.js

feat: rename block

---

bin/bb-rename.cjs
bin/bb.cjs
subcommands/blockRename/index.js
subcommands/blockRename/util.js
subcommands/ls.js
utils/Queries.js
utils/api.js

ls sync status

---

bin/bb-log.cjs
subcommands/logV2/index.js
subcommands/startV2/plugins/handleNodeFunctionStart/index.js
templates/createTemplates/uiContainer-templates/generate-packageJson.js
templates/createTemplates/uiElement-templates/generate-packageJson.js
templates/sample-todo-template-v2/addTodo/package.json
templates/sample-todo-template-v2/listTodos/package.json
templates/sample-todo-template-v2/removeTodo/package.json
templates/sample-todo-template-v2/todoContainer/package.json
templates/sample-todo-template-v2/todoInput/package.json
templates/sample-todo-template-v2/todoItem/package.json
templates/sample-ts-todo-template/addTodo/package.json
templates/sample-ts-todo-template/listTodos/package.json
templates/sample-ts-todo-template/removeTodo/package.json
templates/sample-ts-todo-template/todoContainer/package.json
templates/sample-ts-todo-template/todoInput/package.json
templates/sample-ts-todo-template/todoItem/package.json

Fix logs issues
Fix template issues

fix start and logs issue

---

subcommands/connectRemote/index.js
subcommands/temp-init.js
utils/createRepoV2.js

fix: template and connect remote issues

---

subcommands/startV2/plugins/handleJSViewStart/singleBuild/generateElementsEmulator/generateWebpackConfig.js

refactor: sass configuration

---

subcommands/start/plugins/handleNodeFunctionStart/tsWatcher.js

1.  Added babel for typescript  compile

fix: added babel for typescript compile

---

package.json

version bumped  1.6.3-beta to 1.6.4-beta

fix: version bumped

---

subcommands/pull/plugins/HandleContainerizedPackagePull.js

fix: fixes
